# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tennis Connect' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tennis Connect
    pod 'Parse'
    pod 'Parse/UI'
    pod 'DateTools'
    pod 'MaterialComponents/Buttons'
    pod 'MaterialComponents/Buttons+Theming'
    pod 'MaterialComponents/ActivityIndicator'


  target 'Tennis ConnectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Tennis ConnectUITests' do
    # Pods for testing
  end

end
